// Shared navigation and footer. Keep the markup and behavior in this file.
(function(){
const header=document.getElementById('site-header');
const footer=document.getElementById('site-footer');
const page=document.body.dataset.page||'home';
if(header){const home=page==='home';header.innerHTML=`<a class="site-logo" href="${home?'#top':'index.html'}" aria-label="UAAD home"><img src="UAAD-WHITE.svg" alt="UAAD"></a><nav class="site-nav" aria-label="Primary"><a href="program.html" ${page==='program'||page==='program-item'?'aria-current="page"':''}>Programs</a><a href="stories.html" ${page==='stories'||page==='article'?'aria-current="page"':''}>Stories</a><a href="collaboration.html" ${page==='collaboration'?'aria-current="page"':''}>Collaboration</a><a href="about.html" ${page==='about'?'aria-current="page"':''}>About</a></nav><input class="site-search" id="search" type="search" placeholder="⌕  Search ${home?'projects':page==='program'||page==='program-item'?'programs':'stories'}" aria-label="Search ${home?'projects':page==='program'||page==='program-item'?'programs':'stories'}">`;
const globalSearch=header.querySelector('#search');
// Capture input before legacy page filters so the header always searches the whole site.
header.addEventListener('input',e=>{if(e.target===globalSearch)e.stopImmediatePropagation()},true);
header.addEventListener('keydown',e=>{if(e.target===globalSearch&&e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();const query=globalSearch.value.trim();if(query)location.href='search.html?q='+encodeURIComponent(query)}},true);
requestAnimationFrame(()=>{globalSearch.placeholder='⌕  Search UAAD';globalSearch.setAttribute('aria-label','Search all of UAAD');globalSearch.value=page==='search'?(new URLSearchParams(location.search).get('q')||''):''});
let previous=window.scrollY;window.addEventListener('scroll',()=>{const y=window.scrollY;if(y<90||y<previous-4)header.classList.remove('is-hidden');else if(y>previous+4)header.classList.add('is-hidden');previous=y},{passive:true});}
if(footer){footer.innerHTML=`<video class="site-footer-video" autoplay muted loop playsinline webkit-playsinline disablepictureinpicture preload="auto" aria-hidden="true"><source src="background.mp4" type="video/mp4"></video><div class="site-footer-main"><div class="site-footer-title">Underground<br>Art And Design</div><div class="site-footer-contact"><a href="mailto:hello@uaad.art">HELLO@UAAD.ART</a><div class="site-footer-social"><a href="https://www.instagram.com/uaad.art/" target="_blank" rel="noopener noreferrer">[INSTAGRAM]</a><a href="https://www.youtube.com/channel/UClT5QT-y-EUanu3h0TiiTcA" target="_blank" rel="noopener noreferrer">[YOUTUBE]</a><a href="https://www.linkedin.com/company/underground-art-and-design-llc" target="_blank" rel="noopener noreferrer">[LINKEDIN]</a></div></div></div><div class="site-footer-bottom"><a href="https://www.uaad.art/privacy" target="_blank" rel="noopener noreferrer">PRIVACY POLICY</a><span>TERMS AND CONDITIONS</span><span>© 2026 BY UNDERGROUND ART AND DESIGN</span></div>`;
}
})();


(function(){const header=document.getElementById('site-header');if(!header)return;const nav=header.querySelector('.site-nav'),search=header.querySelector('.site-search'),button=document.createElement('button');button.className='mobile-menu-toggle';button.type='button';button.textContent='[MENU]';button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','mobile-navigation');header.append(button);const panel=document.createElement('div');panel.className='mobile-menu-panel';panel.id='mobile-navigation';panel.hidden=true;const mobileNav=document.createElement('nav');mobileNav.setAttribute('aria-label','Mobile navigation');Array.from(nav.children).forEach(a=>mobileNav.append(a.cloneNode(true)));const form=document.createElement('form');form.action='search.html';form.innerHTML='<input name="q" type="search" placeholder="Search UAAD" aria-label="Search UAAD"><button type="submit">Search ↗</button>';const close=document.createElement('button');close.type='button';close.className='mobile-menu-close';close.textContent='[CLOSE]';panel.append(mobileNav,form,close);document.body.append(panel);function toggle(open){panel.hidden=!open;button.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open);if(open){header.classList.remove('is-hidden');mobileNav.querySelector('a').focus()}else button.focus()}button.addEventListener('click',()=>toggle(panel.hidden));close.addEventListener('click',()=>toggle(false));document.addEventListener('keydown',e=>{if(!panel.hidden&&e.key==='Escape')toggle(false);if(!panel.hidden&&e.key==='Tab'){const links=Array.from(panel.querySelectorAll('a,input,button'));const first=links[0],last=links.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});matchMedia('(max-width:650px)').addEventListener('change',e=>{if(!e.matches&&!panel.hidden)toggle(false)})})();
(function(){const paths={'↗':'M5 19L19 5M5 5h14v14','→':'M4 12h16M13 5l7 7-7 7','←':'M20 12H4M11 5l-7 7 7 7','↓':'M12 4v16M5 13l7 7 7-7','↑':'M12 20V4M5 11l7-7 7 7','↘':'M5 5l14 14M5 19h14V5','↖':'M19 19L5 5M19 5H5v14','↙':'M19 5L5 19M5 5v14h14','➡':'M4 12h16M13 5l7 7-7 7','⬅':'M20 12H4M11 5l-7 7 7 7','⬇':'M12 4v16M5 13l7 7 7-7','⬆':'M12 20V4M5 11l7-7 7 7'};function replace(node){if(!node.parentElement||node.parentElement.closest('script,style,textarea,input,svg'))return;const text=node.nodeValue,regex=/[↗↘↙↖←→↑↓⬅➡⬆⬇][\uFE0E\uFE0F]?/g;if(!regex.test(text))return;regex.lastIndex=0;const fragment=document.createDocumentFragment();let start=0;for(const match of text.matchAll(regex)){fragment.append(document.createTextNode(text.slice(start,match.index)));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class','text-arrow');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',paths[match[0][0]]);svg.append(path);fragment.append(svg);start=match.index+match[0].length}fragment.append(document.createTextNode(text.slice(start)));node.replaceWith(fragment)}function scan(root){if(root.nodeType===3){replace(root);return}const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];let node;while(node=walker.nextNode())nodes.push(node);nodes.forEach(replace)}scan(document.body);new MutationObserver(entries=>entries.forEach(entry=>{if(entry.type==='characterData')replace(entry.target);else entry.addedNodes.forEach(scan)})).observe(document.body,{childList:true,subtree:true,characterData:true})})();

// Use the same inline, silent playback for both background videos.
document.querySelectorAll('.background-video,.site-footer-video').forEach(video=>{
  video.controls=false;video.muted=true;video.defaultMuted=true;video.playsInline=true;video.autoplay=true;
  const play=()=>{const attempt=video.play();if(attempt)attempt.catch(()=>{});};
  video.addEventListener('loadeddata',play);play();
  if('IntersectionObserver' in window)new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)play();else video.pause();}),{threshold:0}).observe(video);
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)play();});
});
